export const PRO_ADD_TO_DETAILS = "PRO_ADD_TO_DETAILS";
export const PRO_ADD_TO_DETAILS_FAILED = "PRO_ADD_TO_DETAILS_FAILED";

export const PRO_ADD_TO_CART = "PRO_ADD_TO_CART_SUCCESS";
export const PRO_ADD_TO_CART_FAILED = "PRO_ADD_TO_CART_FAILED";
